Rebrand Semaphore fork as Job Executor Hub and prepare v0.0.1

diff --git a/deployment/docker/server/server-wrapper b/deployment/docker/server/server-wrapper
--- a/deployment/docker/server/server-wrapper
+++ b/deployment/docker/server/server-wrapper
@@ -34,93 +34,93 @@ file_env() {
     unset "${1}_FILE"
 }
 
-export SEMAPHORE_CONFIG_PATH="${SEMAPHORE_CONFIG_PATH:-/etc/semaphore}"
-export SEMAPHORE_DB_PATH="${SEMAPHORE_DB_PATH:-/var/lib/semaphore}"
-export SEMAPHORE_DB_PORT="${SEMAPHORE_DB_PORT:-}"
+export JEH_CONFIG_PATH="${JEH_CONFIG_PATH:-/etc/jeh}"
+export JEH_DB_PATH="${JEH_DB_PATH:-/var/lib/jeh}"
+export JEH_DB_PORT="${JEH_DB_PORT:-}"
 
-file_env 'SEMAPHORE_DB_USER'
-file_env 'SEMAPHORE_DB_PASS'
-file_env 'SEMAPHORE_ADMIN'
-export SEMAPHORE_ADMIN_EMAIL="${SEMAPHORE_ADMIN_EMAIL:-admin@localhost}"
-export SEMAPHORE_ADMIN_NAME="${SEMAPHORE_ADMIN_NAME:-Semaphore Admin}"
-file_env 'SEMAPHORE_ADMIN_PASSWORD'
-export SEMAPHORE_LDAP_ACTIVATED="${SEMAPHORE_LDAP_ACTIVATED:-no}"
-export SEMAPHORE_LDAP_HOST="${SEMAPHORE_LDAP_HOST:-}"
-export SEMAPHORE_LDAP_PORT="${SEMAPHORE_LDAP_PORT:-}"
-export SEMAPHORE_LDAP_DN_BIND="${SEMAPHORE_LDAP_DN_BIND:-}"
-file_env 'SEMAPHORE_LDAP_PASSWORD'
-export SEMAPHORE_LDAP_DN_SEARCH="${SEMAPHORE_LDAP_DN_SEARCH:-}"
-export SEMAPHORE_LDAP_MAPPING_USERNAME="${SEMAPHORE_LDAP_MAPPING_USERNAME:-uid}"
-export SEMAPHORE_LDAP_MAPPING_FULLNAME="${SEMAPHORE_LDAP_MAPPING_FULLNAME:-cn}"
-export SEMAPHORE_LDAP_MAPPING_EMAIL="${SEMAPHORE_LDAP_MAPPING_EMAIL:-mail}"
-file_env 'SEMAPHORE_ACCESS_KEY_ENCRYPTION'
+file_env 'JEH_DB_USER'
+file_env 'JEH_DB_PASS'
+file_env 'JEH_ADMIN'
+export JEH_ADMIN_EMAIL="${JEH_ADMIN_EMAIL:-admin@localhost}"
+export JEH_ADMIN_NAME="${JEH_ADMIN_NAME:-JEH Admin}"
+file_env 'JEH_ADMIN_PASSWORD'
+export JEH_LDAP_ACTIVATED="${JEH_LDAP_ACTIVATED:-no}"
+export JEH_LDAP_HOST="${JEH_LDAP_HOST:-}"
+export JEH_LDAP_PORT="${JEH_LDAP_PORT:-}"
+export JEH_LDAP_DN_BIND="${JEH_LDAP_DN_BIND:-}"
+file_env 'JEH_LDAP_PASSWORD'
+export JEH_LDAP_DN_SEARCH="${JEH_LDAP_DN_SEARCH:-}"
+export JEH_LDAP_MAPPING_USERNAME="${JEH_LDAP_MAPPING_USERNAME:-uid}"
+export JEH_LDAP_MAPPING_FULLNAME="${JEH_LDAP_MAPPING_FULLNAME:-cn}"
+export JEH_LDAP_MAPPING_EMAIL="${JEH_LDAP_MAPPING_EMAIL:-mail}"
+file_env 'JEH_ACCESS_KEY_ENCRYPTION'
 
 
-[ -d "${SEMAPHORE_CONFIG_PATH}" ] || mkdir -p "${SEMAPHORE_CONFIG_PATH}" || {
-    echo "Can't create Semaphore config path ${SEMAPHORE_CONFIG_PATH}."
+[ -d "${JEH_CONFIG_PATH}" ] || mkdir -p "${JEH_CONFIG_PATH}" || {
+    echo "Can't create JEH config path ${JEH_CONFIG_PATH}."
     exit 1
 }
 
-[ -d "${SEMAPHORE_DB_PATH}" ] || mkdir -p "${SEMAPHORE_DB_PATH}" || {
-    echo "Can't create Semaphore data path ${SEMAPHORE_DB_PATH}."
+[ -d "${JEH_DB_PATH}" ] || mkdir -p "${JEH_DB_PATH}" || {
+    echo "Can't create JEH data path ${JEH_DB_PATH}."
     exit 1
 }
 
 
 #
 # Extract database host and port from config.json if they are not set.
-# Set default SEMAPHORE_DB_DIALECT and SEMAPHORE_DB_HOST if empty.
+# Set default JEH_DB_DIALECT and JEH_DB_HOST if empty.
 #
-if [ -z "${SEMAPHORE_DB_DIALECT}" ]; then
-    if [ -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
-        SEMAPHORE_DB_DIALECT=$(cat "${SEMAPHORE_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
+if [ -z "${JEH_DB_DIALECT}" ]; then
+    if [ -f "${JEH_CONFIG_PATH}/config.json" ]; then
+        JEH_DB_DIALECT=$(cat "${JEH_CONFIG_PATH}/config.json" | jq '.dialect // ""' -r)
     fi
 fi
 
-export SEMAPHORE_DB_DIALECT="${SEMAPHORE_DB_DIALECT:-mysql}"
+export JEH_DB_DIALECT="${JEH_DB_DIALECT:-mysql}"
 
-if [ -z "${SEMAPHORE_DB_HOST}" ]; then
-    if [ -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
-        SEMAPHORE_DB_HOST=$(cat "${SEMAPHORE_CONFIG_PATH}/config.json" | jq ".${SEMAPHORE_DB_DIALECT}.host // \"\"" -r)
+if [ -z "${JEH_DB_HOST}" ]; then
+    if [ -f "${JEH_CONFIG_PATH}/config.json" ]; then
+        JEH_DB_HOST=$(cat "${JEH_CONFIG_PATH}/config.json" | jq ".${JEH_DB_DIALECT}.host // \"\"" -r)
     fi
 fi
 
-if [ -z "${SEMAPHORE_DB_HOST}" ]; then
-    if [ "${SEMAPHORE_DB_DIALECT}" = 'sqlite' ]; then
-        export SEMAPHORE_DB_HOST=${SEMAPHORE_DB_PATH}/database.sqlite
+if [ -z "${JEH_DB_HOST}" ]; then
+    if [ "${JEH_DB_DIALECT}" = 'sqlite' ]; then
+        export JEH_DB_HOST=${JEH_DB_PATH}/database.sqlite
     else
-        export SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST:-0.0.0.0}"
+        export JEH_DB_HOST="${JEH_DB_HOST:-0.0.0.0}"
     fi
 fi
 
 
 #
-# Remove port number from SEMAPHORE_DB_HOST and put it to SEMAPHORE_DB_PORT
+# Remove port number from JEH_DB_HOST and put it to JEH_DB_PORT
 #
-case "$SEMAPHORE_DB_HOST" in
+case "$JEH_DB_HOST" in
   *:*)
-    SEMAPHORE_DB_PORT=$(echo "$SEMAPHORE_DB_HOST" | cut -d ':' -f 2)
-    SEMAPHORE_DB_HOST=$(echo "$SEMAPHORE_DB_HOST" | cut -d ':' -f 1)
+    JEH_DB_PORT=$(echo "$JEH_DB_HOST" | cut -d ':' -f 2)
+    JEH_DB_HOST=$(echo "$JEH_DB_HOST" | cut -d ':' -f 1)
     ;;
   *)
 esac
 
 
 #
-# Set SEMAPHORE_DB_PORT if it is not set
+# Set JEH_DB_PORT if it is not set
 #
-if [ -z "${SEMAPHORE_DB_PORT}" ]; then
-    case ${SEMAPHORE_DB_DIALECT} in
+if [ -z "${JEH_DB_PORT}" ]; then
+    case ${JEH_DB_DIALECT} in
         mysql)
-            SEMAPHORE_DB_PORT=3306
+            JEH_DB_PORT=3306
             ;;
         postgres)
-            SEMAPHORE_DB_PORT=5432
+            JEH_DB_PORT=5432
             ;;
         sqlite)
             ;;
         *)
-            echoerr "Unknown database dialect: ${SEMAPHORE_DB_DIALECT}"
+            echoerr "Unknown database dialect: ${JEH_DB_DIALECT}"
             exit 1
             ;;
     esac
@@ -130,12 +130,12 @@ fi
 #
 # Ping database if it is not BoltDB
 #
-if [ "${SEMAPHORE_DB_DIALECT}" != 'sqlite' ]; then
-    echoerr "Pinging database on ${SEMAPHORE_DB_HOST} port ${SEMAPHORE_DB_PORT}..."
+if [ "${JEH_DB_DIALECT}" != 'sqlite' ]; then
+    echoerr "Pinging database on ${JEH_DB_HOST} port ${JEH_DB_PORT}..."
     TIMEOUT=30
 
 
-    while ! $(nc -z "$SEMAPHORE_DB_HOST" "$SEMAPHORE_DB_PORT") >/dev/null 2>&1; do
+    while ! $(nc -z "$JEH_DB_HOST" "$JEH_DB_PORT") >/dev/null 2>&1; do
         TIMEOUT=$(expr $TIMEOUT - 1)
 
         if [ $TIMEOUT -eq 0 ]; then
@@ -147,100 +147,100 @@ if [ "${SEMAPHORE_DB_DIALECT}" != 'sqlite' ]; then
         sleep 1
     done
     
-    export SEMAPHORE_DB_HOST="${SEMAPHORE_DB_HOST}:${SEMAPHORE_DB_PORT}"
+    export JEH_DB_HOST="${JEH_DB_HOST}:${JEH_DB_PORT}"
 fi
 
 
 #
 # Generate new config.json if it does not exist
 #
-SEMAPHORE_FIRST_RUN=no
-if [ ! -f "${SEMAPHORE_CONFIG_PATH}/config.json" ]; then
-    SEMAPHORE_FIRST_RUN=yes
+JEH_FIRST_RUN=no
+if [ ! -f "${JEH_CONFIG_PATH}/config.json" ]; then
+    JEH_FIRST_RUN=yes
     echoerr "Generating setup file ${TMP_STDIN_CONFIG_FILE} ..."
 
     TMP_STDIN_CONFIG_FILE=$(mktemp)
 
 
-    SEMAPHORE_TMP_PATH=${SEMAPHORE_TMP_PATH:-/tmp/semaphore}
-    [ -d "${SEMAPHORE_TMP_PATH}" ] || mkdir -p "${SEMAPHORE_TMP_PATH}" || {
-        echo "Can't create Semaphore tmp path ${SEMAPHORE_TMP_PATH}."
+    JEH_TMP_PATH=${JEH_TMP_PATH:-/tmp/jeh}
+    [ -d "${JEH_TMP_PATH}" ] || mkdir -p "${JEH_TMP_PATH}" || {
+        echo "Can't create JEH tmp path ${JEH_TMP_PATH}."
         exit 1
     }
 
 
-    case ${SEMAPHORE_DB_DIALECT} in
+    case ${JEH_DB_DIALECT} in
         mysql)
-            SEMAPHORE_DB_DIALECT_ID=1
+            JEH_DB_DIALECT_ID=1
             ;;
         postgres)
-            SEMAPHORE_DB_DIALECT_ID=3
+            JEH_DB_DIALECT_ID=3
             ;;
         sqlite)
-            SEMAPHORE_DB_DIALECT_ID=4
+            JEH_DB_DIALECT_ID=4
             ;;
         *)
-            echoerr "Unknown database dialect: ${SEMAPHORE_DB_DIALECT}"
+            echoerr "Unknown database dialect: ${JEH_DB_DIALECT}"
             exit 1
             ;;
     esac
 
 
     cat << EOF > "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_DIALECT_ID}
+${JEH_DB_DIALECT_ID}
 EOF
 
-    if [ "${SEMAPHORE_DB_DIALECT}" = "sqlite" ]; then
+    if [ "${JEH_DB_DIALECT}" = "sqlite" ]; then
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_HOST}
+${JEH_DB_HOST}
 EOF
     else
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_DB_HOST}
-${SEMAPHORE_DB_USER}
-${SEMAPHORE_DB_PASS}
-${SEMAPHORE_DB:-semaphore}
+${JEH_DB_HOST}
+${JEH_DB_USER}
+${JEH_DB_PASS}
+${JEH_DB:-jeh}
 EOF
     fi
 
     cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_TMP_PATH}
-${SEMAPHORE_WEB_ROOT:-}
+${JEH_TMP_PATH}
+${JEH_WEB_ROOT:-}
 no
 no
 no
 no
 no
-${SEMAPHORE_LDAP_ACTIVATED}
+${JEH_LDAP_ACTIVATED}
 EOF
 
-    if [ "${SEMAPHORE_LDAP_ACTIVATED}" = "yes" ]; then
+    if [ "${JEH_LDAP_ACTIVATED}" = "yes" ]; then
         cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_LDAP_HOST}:${SEMAPHORE_LDAP_PORT}
-${SEMAPHORE_LDAP_NEEDTLS:-no}
-${SEMAPHORE_LDAP_DN_BIND}
-${SEMAPHORE_LDAP_PASSWORD}
-${SEMAPHORE_LDAP_DN_SEARCH}
-${SEMAPHORE_LDAP_SEARCH_FILTER:-(uid=%s)}
-${SEMAPHORE_LDAP_MAPPING_DN:-dn}
-${SEMAPHORE_LDAP_MAPPING_USERNAME}
-${SEMAPHORE_LDAP_MAPPING_FULLNAME}
-${SEMAPHORE_LDAP_MAPPING_EMAIL}
+${JEH_LDAP_HOST}:${JEH_LDAP_PORT}
+${JEH_LDAP_NEEDTLS:-no}
+${JEH_LDAP_DN_BIND}
+${JEH_LDAP_PASSWORD}
+${JEH_LDAP_DN_SEARCH}
+${JEH_LDAP_SEARCH_FILTER:-(uid=%s)}
+${JEH_LDAP_MAPPING_DN:-dn}
+${JEH_LDAP_MAPPING_USERNAME}
+${JEH_LDAP_MAPPING_FULLNAME}
+${JEH_LDAP_MAPPING_EMAIL}
 EOF
     fi;
 
     cat << EOF >> "${TMP_STDIN_CONFIG_FILE}"
-${SEMAPHORE_CONFIG_PATH}
-${SEMAPHORE_ADMIN}
-${SEMAPHORE_ADMIN_EMAIL}
-${SEMAPHORE_ADMIN_NAME}
-${SEMAPHORE_ADMIN_PASSWORD}
+${JEH_CONFIG_PATH}
+${JEH_ADMIN}
+${JEH_ADMIN_EMAIL}
+${JEH_ADMIN_NAME}
+${JEH_ADMIN_PASSWORD}
 EOF
 
 
-    echoerr "Executing semaphore setup"
+    echoerr "Executing jeh setup"
     if test "$#" -ne 1; then
-        /usr/local/bin/semaphore setup - < "${TMP_STDIN_CONFIG_FILE}"
+        /usr/local/bin/jeh setup - < "${TMP_STDIN_CONFIG_FILE}"
     else
         "$1" setup - < "${TMP_STDIN_CONFIG_FILE}"
     fi
@@ -251,51 +251,51 @@ fi
 #
 # Install additional python dependencies
 #
-if test -f "${SEMAPHORE_CONFIG_PATH}/requirements.txt"; then
+if test -f "${JEH_CONFIG_PATH}/requirements.txt"; then
     echoerr "Installing additional python dependencies"
     pip3 install --upgrade \
-        -r "${SEMAPHORE_CONFIG_PATH}/requirements.txt"
+        -r "${JEH_CONFIG_PATH}/requirements.txt"
 else
     echoerr "No additional python dependencies to install"
 fi
 
 #
-# Migrate from BoltDB if SEMAPHORE_MIGRATE_FROM_BOLTDB is set (first run only, SQLite only, skipped if DB file already exists)
+# Migrate from BoltDB if JEH_MIGRATE_FROM_BOLTDB is set (first run only, SQLite only, skipped if DB file already exists)
 #
-case "${SEMAPHORE_MIGRATE_FROM_BOLTDB:-}" in
+case "${JEH_MIGRATE_FROM_BOLTDB:-}" in
     [Tt][Rr][Uu][Ee]|[Yy][Ee][Ss])
-        SEMAPHORE_MIGRATE_FROM_BOLTDB="${SEMAPHORE_DB_PATH}/database.boltdb"
+        JEH_MIGRATE_FROM_BOLTDB="${JEH_DB_PATH}/database.boltdb"
         ;;
 esac
 
-if [ -n "${SEMAPHORE_MIGRATE_FROM_BOLTDB:-}" ] && [ "${SEMAPHORE_FIRST_RUN}" = "yes" ]; then
-    if [ "${SEMAPHORE_DB_DIALECT}" != "sqlite" ]; then
-        echoerr "SEMAPHORE_MIGRATE_FROM_BOLTDB is only supported with SQLite dialect, ignoring"
+if [ -n "${JEH_MIGRATE_FROM_BOLTDB:-}" ] && [ "${JEH_FIRST_RUN}" = "yes" ]; then
+    if [ "${JEH_DB_DIALECT}" != "sqlite" ]; then
+        echoerr "JEH_MIGRATE_FROM_BOLTDB is only supported with SQLite dialect, ignoring"
     else
-        echoerr "Migrating from BoltDB: ${SEMAPHORE_MIGRATE_FROM_BOLTDB}"
-        MIGRATE_ARGS="--from-boltdb=${SEMAPHORE_MIGRATE_FROM_BOLTDB} --merge-existing-users"
-        if [ -n "${SEMAPHORE_MIGRATE_SKIP_TASK_OUTPUT:-}" ]; then
+        echoerr "Migrating from BoltDB: ${JEH_MIGRATE_FROM_BOLTDB}"
+        MIGRATE_ARGS="--from-boltdb=${JEH_MIGRATE_FROM_BOLTDB} --merge-existing-users"
+        if [ -n "${JEH_MIGRATE_SKIP_TASK_OUTPUT:-}" ]; then
             MIGRATE_ARGS="${MIGRATE_ARGS} --skip-task-output"
         fi
         if test "$#" -ne 1; then
-            /usr/local/bin/semaphore migrate ${MIGRATE_ARGS} --config "${SEMAPHORE_CONFIG_PATH}/config.json"
+            /usr/local/bin/jeh migrate ${MIGRATE_ARGS} --config "${JEH_CONFIG_PATH}/config.json"
         else
-            "$1" migrate ${MIGRATE_ARGS} --config "${SEMAPHORE_CONFIG_PATH}/config.json"
+            "$1" migrate ${MIGRATE_ARGS} --config "${JEH_CONFIG_PATH}/config.json"
         fi
     fi
 fi
 
-# Import project if environment variable SEMAPHORE_IMPORT_PROJECT_FILE is defined.
-# Optionally use SEMAPHORE_IMPORT_PROJECT_NAME to specify the project name.
-if [ -n "${SEMAPHORE_IMPORT_PROJECT_FILE:-}" ] && [ "${SEMAPHORE_FIRST_RUN}" = "yes" ]; then
-    echoerr "Importing project from ${SEMAPHORE_IMPORT_PROJECT_FILE}"
-    IMPORT_ARGS="--file ${SEMAPHORE_IMPORT_PROJECT_FILE}"
-    if [ -n "${SEMAPHORE_IMPORT_PROJECT_NAME:-}" ]; then
-        echoerr "Using project name: ${SEMAPHORE_IMPORT_PROJECT_NAME}"
-        IMPORT_ARGS="${IMPORT_ARGS} --project-name ${SEMAPHORE_IMPORT_PROJECT_NAME}"
+# Import project if environment variable JEH_IMPORT_PROJECT_FILE is defined.
+# Optionally use JEH_IMPORT_PROJECT_NAME to specify the project name.
+if [ -n "${JEH_IMPORT_PROJECT_FILE:-}" ] && [ "${JEH_FIRST_RUN}" = "yes" ]; then
+    echoerr "Importing project from ${JEH_IMPORT_PROJECT_FILE}"
+    IMPORT_ARGS="--file ${JEH_IMPORT_PROJECT_FILE}"
+    if [ -n "${JEH_IMPORT_PROJECT_NAME:-}" ]; then
+        echoerr "Using project name: ${JEH_IMPORT_PROJECT_NAME}"
+        IMPORT_ARGS="${IMPORT_ARGS} --project-name ${JEH_IMPORT_PROJECT_NAME}"
     fi
     if test "$#" -ne 1; then
-        /usr/local/bin/semaphore project import ${IMPORT_ARGS} --config "${SEMAPHORE_CONFIG_PATH}/config.json" || echoerr "Project import failed"
+        /usr/local/bin/jeh project import ${IMPORT_ARGS} --config "${JEH_CONFIG_PATH}/config.json" || echoerr "Project import failed"
     else
         "$1" project import ${IMPORT_ARGS} || echoerr "Project import failed"
     fi
@@ -303,11 +303,11 @@ fi
 
 
 #
-# Start Semaphore server
+# Start JEH server
 #
-echoerr "Starting semaphore server"
+echoerr "Starting jeh server"
 if test "$#" -ne 1; then
-    exec /usr/local/bin/semaphore server --config "${SEMAPHORE_CONFIG_PATH}/config.json"
+    exec /usr/local/bin/jeh server --config "${JEH_CONFIG_PATH}/config.json"
 else
     exec "$@"
 fi
